// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dbinom
NumericVector dbinom(NumericVector x, double size, double prob, bool log);
RcppExport SEXP _exactr_dbinom(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dbinom(x, size, prob, log));
    return rcpp_result_gen;
END_RCPP
}
// pbinom_cpp
NumericVector pbinom_cpp(NumericVector q, double size, double prob, bool lower_tail, bool log_p, bool midp, bool approx, double prob_denom);
RcppExport SEXP _exactr_pbinom_cpp(SEXP qSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP, SEXP midpSEXP, SEXP approxSEXP, SEXP prob_denomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    Rcpp::traits::input_parameter< bool >::type midp(midpSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< double >::type prob_denom(prob_denomSEXP);
    rcpp_result_gen = Rcpp::wrap(pbinom_cpp(q, size, prob, lower_tail, log_p, midp, approx, prob_denom));
    return rcpp_result_gen;
END_RCPP
}
// qbinom_cpp
NumericVector qbinom_cpp(NumericVector p, double size, double prob, bool lower_tail, bool log_p);
RcppExport SEXP _exactr_qbinom_cpp(SEXP pSEXP, SEXP sizeSEXP, SEXP probSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(qbinom_cpp(p, size, prob, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// binom_test_lnpval
double binom_test_lnpval(double x_round, double size_round, double prob, bool midp, double prob_denom);
RcppExport SEXP _exactr_binom_test_lnpval(SEXP x_roundSEXP, SEXP size_roundSEXP, SEXP probSEXP, SEXP midpSEXP, SEXP prob_denomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x_round(x_roundSEXP);
    Rcpp::traits::input_parameter< double >::type size_round(size_roundSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    Rcpp::traits::input_parameter< bool >::type midp(midpSEXP);
    Rcpp::traits::input_parameter< double >::type prob_denom(prob_denomSEXP);
    rcpp_result_gen = Rcpp::wrap(binom_test_lnpval(x_round, size_round, prob, midp, prob_denom));
    return rcpp_result_gen;
END_RCPP
}
// dhyper
NumericVector dhyper(NumericVector x, double m, double n, double k, bool log);
RcppExport SEXP _exactr_dhyper(SEXP xSEXP, SEXP mSEXP, SEXP nSEXP, SEXP kSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dhyper(x, m, n, k, log));
    return rcpp_result_gen;
END_RCPP
}
// phyper_cpp
NumericVector phyper_cpp(NumericVector q, double m, double n, double k, bool lower_tail, bool log_p, bool midp, bool approx);
RcppExport SEXP _exactr_phyper_cpp(SEXP qSEXP, SEXP mSEXP, SEXP nSEXP, SEXP kSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP, SEXP midpSEXP, SEXP approxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    Rcpp::traits::input_parameter< bool >::type midp(midpSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    rcpp_result_gen = Rcpp::wrap(phyper_cpp(q, m, n, k, lower_tail, log_p, midp, approx));
    return rcpp_result_gen;
END_RCPP
}
// qhyper_cpp
NumericVector qhyper_cpp(NumericVector p, double m, double n, double k, bool lower_tail, bool log_p);
RcppExport SEXP _exactr_qhyper_cpp(SEXP pSEXP, SEXP mSEXP, SEXP nSEXP, SEXP kSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(qhyper_cpp(p, m, n, k, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// fisher23_test_lnpval
double fisher23_test_lnpval(IntegerMatrix x, bool midp);
RcppExport SEXP _exactr_fisher23_test_lnpval(SEXP xSEXP, SEXP midpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type midp(midpSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher23_test_lnpval(x, midp));
    return rcpp_result_gen;
END_RCPP
}
// fisher22_test_lnpval
double fisher22_test_lnpval(double x11, double x12, double x21, double x22, int32_t midp);
RcppExport SEXP _exactr_fisher22_test_lnpval(SEXP x11SEXP, SEXP x12SEXP, SEXP x21SEXP, SEXP x22SEXP, SEXP midpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x11(x11SEXP);
    Rcpp::traits::input_parameter< double >::type x12(x12SEXP);
    Rcpp::traits::input_parameter< double >::type x21(x21SEXP);
    Rcpp::traits::input_parameter< double >::type x22(x22SEXP);
    Rcpp::traits::input_parameter< int32_t >::type midp(midpSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher22_test_lnpval(x11, x12, x21, x22, midp));
    return rcpp_result_gen;
END_RCPP
}
// odds_ratio_22
double odds_ratio_22(double x11, double x12, double x21, double x22);
RcppExport SEXP _exactr_odds_ratio_22(SEXP x11SEXP, SEXP x12SEXP, SEXP x21SEXP, SEXP x22SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x11(x11SEXP);
    Rcpp::traits::input_parameter< double >::type x12(x12SEXP);
    Rcpp::traits::input_parameter< double >::type x21(x21SEXP);
    Rcpp::traits::input_parameter< double >::type x22(x22SEXP);
    rcpp_result_gen = Rcpp::wrap(odds_ratio_22(x11, x12, x21, x22));
    return rcpp_result_gen;
END_RCPP
}
// odds_ratio_ci_22
NumericVector odds_ratio_ci_22(double x11, double x12, double x21, double x22, double low, double high);
RcppExport SEXP _exactr_odds_ratio_ci_22(SEXP x11SEXP, SEXP x12SEXP, SEXP x21SEXP, SEXP x22SEXP, SEXP lowSEXP, SEXP highSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x11(x11SEXP);
    Rcpp::traits::input_parameter< double >::type x12(x12SEXP);
    Rcpp::traits::input_parameter< double >::type x21(x21SEXP);
    Rcpp::traits::input_parameter< double >::type x22(x22SEXP);
    Rcpp::traits::input_parameter< double >::type low(lowSEXP);
    Rcpp::traits::input_parameter< double >::type high(highSEXP);
    rcpp_result_gen = Rcpp::wrap(odds_ratio_ci_22(x11, x12, x21, x22, low, high));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exactr_dbinom", (DL_FUNC) &_exactr_dbinom, 4},
    {"_exactr_pbinom_cpp", (DL_FUNC) &_exactr_pbinom_cpp, 8},
    {"_exactr_qbinom_cpp", (DL_FUNC) &_exactr_qbinom_cpp, 5},
    {"_exactr_binom_test_lnpval", (DL_FUNC) &_exactr_binom_test_lnpval, 5},
    {"_exactr_dhyper", (DL_FUNC) &_exactr_dhyper, 5},
    {"_exactr_phyper_cpp", (DL_FUNC) &_exactr_phyper_cpp, 8},
    {"_exactr_qhyper_cpp", (DL_FUNC) &_exactr_qhyper_cpp, 6},
    {"_exactr_fisher23_test_lnpval", (DL_FUNC) &_exactr_fisher23_test_lnpval, 2},
    {"_exactr_fisher22_test_lnpval", (DL_FUNC) &_exactr_fisher22_test_lnpval, 5},
    {"_exactr_odds_ratio_22", (DL_FUNC) &_exactr_odds_ratio_22, 4},
    {"_exactr_odds_ratio_ci_22", (DL_FUNC) &_exactr_odds_ratio_ci_22, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_exactr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
