# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Binomial distribution pmf
#'
#' Mass function for binomial distribution with parameters `size` and `prob`.
#' Implementation is based on log-factorial functions utilizing the QD
#' high-precision library.
#'
#' @references Hida Y, Li XS, Bailey DH (2001) Algorithms for quad-double
#'   precision floating point arithmetic.  Proceedings of the 15th IEEE
#'   Symposium on Computer Arithmetic.
#'
#' @param x vector of success counts.
#' @param size number of trials (zero or more).
#' @param prob probability of success on each trial.
#' @param log logical; if TRUE, probabilities are returned as logarithms.
#' @return pmf(x).
#' @export
dbinom <- function(x, size, prob = 0.5, log = FALSE) {
    .Call(`_exactr_dbinom`, x, size, prob, log)
}

#' @title Binomial distribution cmf
#' @description Backend for pbinom(), separated since dots aren't permitted in
#'   C++ parameter names.
#' @noRd
pbinom_cpp <- function(q, size, prob, lower_tail, log_p, midp, approx, prob_denom) {
    .Call(`_exactr_pbinom_cpp`, q, size, prob, lower_tail, log_p, midp, approx, prob_denom)
}

#' @title Binomial distribution ppf
#' @description Backend for qbinom(), separated since dots aren't permitted in
#'   C++ parameter names.
#' @noRd
qbinom_cpp <- function(p, size, prob, lower_tail, log_p) {
    .Call(`_exactr_qbinom_cpp`, p, size, prob, lower_tail, log_p)
}

#' @title Exact binomial two-sided test p-value
#' @description Implements main p-value calculation for 2-sided binom.test().
#' @noRd
binom_2sided_pval <- function(x_round, size_round, prob, midp, log_p, prob_denom) {
    .Call(`_exactr_binom_2sided_pval`, x_round, size_round, prob, midp, log_p, prob_denom)
}

#' Hypergeometric distribution pmf
#'
#' Mass function for hypergeometric distribution with parameters `m`, `n`, and
#' `k`.  Implementation is based on log-factorial functions utilizing the QD
#' high-precision library.
#'
#' @references Hida Y, Li XS, Bailey DH (2001) Algorithms for quad-double
#'   precision floating point arithmetic.  Proceedings of the 15th IEEE
#'   Symposium on Computer Arithmetic.
#'
#' @param x vector which can be interpreted as numbers of white balls drawn
#'   without replacement from an urn which contains both black and white
#'   balls.
#' @param m the number of white balls in the urn.
#' @param n the number of black balls in the urn.
#' @param k the number of balls drawn from the urn, must be in \[0, m+n\].
#' @param log logical; if TRUE, probabilities are returned as logarithms.
#' @return pmf(x).
#' @export
dhyper <- function(x, m, n, k, log = FALSE) {
    .Call(`_exactr_dhyper`, x, m, n, k, log)
}

#' @title Hypergeometric distribution cmf
#' @description Backend for phyper(), separated since dots aren't permitted in
#'   C++ parameter names.
#' @noRd
phyper_cpp <- function(q, m, n, k, lower_tail, log_p, midp, approx) {
    .Call(`_exactr_phyper_cpp`, q, m, n, k, lower_tail, log_p, midp, approx)
}

#' @title Hypergeometric distribution ppf
#' @description Backend for qbinom(), separated since dots aren't permitted in
#'   C++ parameter names.
#' @noRd
qhyper_cpp <- function(p, m, n, k, lower_tail, log_p) {
    .Call(`_exactr_qhyper_cpp`, p, m, n, k, lower_tail, log_p)
}

#' @title Fisher 2x3 test log-p-value
#' @description Implements main p-value calculation for 2x3 tables.
#' @noRd
fisher23_test_pval <- function(x, midp, log_p) {
    .Call(`_exactr_fisher23_test_pval`, x, midp, log_p)
}

#' @title Fisher 2x2 two-sided test p-value
#' @description Implements main two-sided p-value calculation for 2x2 tables.
#' @noRd
fisher22_2sided_pval <- function(x11, x12, x21, x22, midp, log_p) {
    .Call(`_exactr_fisher22_2sided_pval`, x11, x12, x21, x22, midp, log_p)
}

#' @title Fisher 2x2 one-sided test p-value, nonstandard odds ratio
#' @description This is equivalent to evaluation of the Fisher's noncentral
#'   hypergeometric distribution cdf.
#' @noRd
fisher22_1sided_pval_ex <- function(x11, x12, x21, x22, odds, lower_tail, midp, log_p) {
    .Call(`_exactr_fisher22_1sided_pval_ex`, x11, x12, x21, x22, odds, lower_tail, midp, log_p)
}

#' @title Fisher 2x2 two-sided test p-value, nonstandard odds ratio
#' @description Implements main two-sided p-value calculation for 2x2 tables
#'   with hypothesized odds!=1.
#' @noRd
fisher22_2sided_pval_ex <- function(x11, x12, x21, x22, odds, midp, log_p, odds_denom) {
    .Call(`_exactr_fisher22_2sided_pval_ex`, x11, x12, x21, x22, odds, midp, log_p, odds_denom)
}

#' @title Odds ratio, 2x2 table
#' @description Implements odds ratio point-estimate for 2x2 tables.
#' @noRd
odds_ratio_22 <- function(x11, x12, x21, x22) {
    .Call(`_exactr_odds_ratio_22`, x11, x12, x21, x22)
}

#' @title Odds ratio confidence interval, 2x2 table
#' @description Implements odds ratio confidence-interval calculation for 2x2
#'   tables.
#' @noRd
odds_ratio_ci_22 <- function(x11, x12, x21, x22, low, high) {
    .Call(`_exactr_odds_ratio_ci_22`, x11, x12, x21, x22, low, high)
}

