# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Binomial distribution pmf
#'
#' Mass function for binomial distribution with parameters `size` and `prob`.
#' Implementation is based on log-factorial functions utilizing the QD
#' high-precision library.
#'
#' @references Hida Y, Li XS, Bailey DH (2001) Algorithms for quad-double
#'   precision floating point arithmetic.  Proceedings of the 15th IEEE
#'   Symposium on Computer Arithmetic.
#'
#' @param x vector of success counts.
#' @param size number of trials (zero or more).
#' @param prob probability of success on each trial.
#' @param log logical; if TRUE, probabilities are returned as logarithms.
#' @return pmf(x).
#' @export
dbinom <- function(x, size, prob = 0.5, log = FALSE) {
    .Call(`_exactr_dbinom`, x, size, prob, log)
}

#' @title Binomial distribution cmf
#' @description Backend for pbinom()
#' @noRd
pbinom_cpp <- function(q, size, prob = 0.5, lower_tail = TRUE, log_p = FALSE, approx = FALSE) {
    .Call(`_exactr_pbinom_cpp`, q, size, prob, lower_tail, log_p, approx)
}

