// Copyright (C) 2026 Christopher Chang.
//
// This library is free software: you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as published by the
// Free Software Foundation; either version 3 of the License, or (at your
// option) any later version.
//
// This library is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
// for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this library.  If not, see <http://www.gnu.org/licenses/>.

#include "special_func.h"

#include <assert.h>
#include <math.h>

#include "plink2_base.h"
#include "plink2_float.h"

#ifdef __cplusplus
namespace plink2 {
#endif

// float64- (and a few higher-precision) routines for evaluating special
// functions.  Currently touches beta and inverse-error.


// ibeta_...() and dependencies below are adapted from Boost 1.91.0.
// This derived code is subject to the following license:
//
// *****
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// *****

// static const double kLentzFpmin = DBL_MIN * 16;

// this depends on the polynomial coefficients above
// exactly 808618867 * 2^{-27}, don't need to represent this as dd_real
static const double kLanczosDoubleG = 6.024680040776729583740234375;

double lanczos_sum_d_expg_scaled_imp(double zz, double* s2_ptr) {
  // zz currently guaranteed to be >1.
  zz = 1 / zz;
  const double s1 = POLY12(zz,
                           0.006061842346248907,
                           0.5098416655656676,
                           19.519927882476175,
                           449.9445569063168,
                           6955.999602515376,
                           75999.29304014542,
                           601859.6171681099,
                           3481712.154980646,
                           14605578.087685067,
                           43338889.32467614,
                           86363131.2881386,
                           103794043.11634454,
                           56906521.913471565);
  *s2_ptr = POLY11(zz,
                   1,
                   66,
                   1925,
                   32670,
                   357423,
                   2637558,
                   13339535,
                   45995730,
                   105258076,
                   150917976,
                   120543840,
                   39916800);
  return s1;
}

dd_real ibeta_power_terms_d_ln(double aa, double bb, dd_real p_ddr, dd_real q_ddr, dd_real aq_minus_bp_ddr) {
  // Returns log((p^a)(q^b) / Beta(a,b))
  //       = log((p^a)(q^b)(a+b-1)! / ((a-1)!(b-1)!)).
  //
  // This actually holds up better than the obvious ddr-based implementation
  // when aa+bb approaches 2^52.
  double cc = aa + bb;
  const double gh = kLanczosDoubleG - 0.5;
  const dd_real agh_ddr = ddr_add2d(gh, aa);
  const dd_real bgh_ddr = ddr_add2d(gh, bb);
  const dd_real cgh_ddr = ddr_add2d(gh, cc);

  double numer_a;
  const double denom_a = lanczos_sum_d_expg_scaled_imp(aa, &numer_a);
  double numer_b;
  const double denom_b = lanczos_sum_d_expg_scaled_imp(bb, &numer_b);
  double denom_c;
  const double numer_c = lanczos_sum_d_expg_scaled_imp(cc, &denom_c);
  // Tried performing some of the following computations with float64s instead
  // of dd_reals, but that resulted in noticeably higher error than scipy.
  const dd_real term1_ddr =
    ddr_sqr(
      ddr_accurate_div(ddr_muld(ddr_mul2d(numer_a, numer_b), numer_c),
                       ddr_muld(ddr_mul2d(denom_a, denom_b), denom_c)));
  const dd_real term2_ddr =
    ddr_accurate_div(ddr_mul(agh_ddr, bgh_ddr),
                     ddr_mul(cgh_ddr, _ddr_e));
  dd_real result_ddr =
    ddr_mul_pwr2(ddr_log(ddr_mul(term1_ddr, term2_ddr)),
                 0.5);

  // Calculate l1 and l2 with extra precision, since magnitude can greatly
  // exceed that of ln(result).
  // This removes the need for special cases.
  const dd_real l1_ddr =
    ddr_accurate_div(ddr_negate(ddr_add(aq_minus_bp_ddr,
                                        ddr_muld(q_ddr, gh))),
                     agh_ddr);
  const dd_real l2_ddr =
    ddr_accurate_div(ddr_sub(aq_minus_bp_ddr,
                             ddr_muld(p_ddr, gh)),
                     bgh_ddr);
  return ddr_sort_and_add3(result_ddr,
                           ddr_muld(ddr_log1p(l1_ddr), aa),
                           ddr_muld(ddr_log1p(l2_ddr), bb));
}

double ibeta_continued_fraction_recip_d(double aa, double bb, double xx, double yy, dd_real ay_minus_bx_ddr, uint32_t inv, uint32_t midp_complement) {
  // see Boost continued_fraction_b()
  const double ay_minus_bx_plus1 = ay_minus_bx_ddr.x[0] + 1.0;
  double cc = (aa / (aa + 1.0)) * ay_minus_bx_plus1;
  const double two_minus_x = 2 - xx;
  // This provides a noticeable accuracy boost at reasonable computational
  // cost.
  dd_real ff_ddr = ddr_maked(cc);
  double dd = 0.0;
  double mm = 1.0;
  while (1) {
    const double denom = aa + 2 * mm - 1;
    // if xx is very small, precomputed xx * xx may underflow when actual
    // product here does not
    // (also possible for actual product to underflow)
    const double shared_middle_term = mm * (bb - mm) * xx / denom;
    const double cur_a = ((aa + mm - 1) / denom) * (aa + bb + mm - 1) * shared_middle_term * xx;
    double cur_b = prefer_fma((aa + mm) / (aa + 2 * mm + 1), prefer_fma(mm, two_minus_x, ay_minus_bx_plus1), mm + shared_middle_term);
    // cur_b += ((aa + mm) / (aa + 2 * mm + 1)) * prefer_fma(mm, two_minus_x, ay_minus_bx_plus1);
    mm += 1.0;
    dd = prefer_fma(cur_a, dd, cur_b);
    // Algorithm should terminate when cur_a decreases to 0 due to bb == mm or
    // underflow.  At and before that point, cur_b is always positive.
    /*
    if (dd == 0.0) {
      dd = kLentzFpmin;
    }
    */
    cc = cur_b + cur_a / cc;
    /*
    if (cc == 0.0) {
      cc = kLentzFpmin;
    }
    */
    dd = 1.0 / dd;
    const dd_real delta_ddr = ddr_mul2d(cc, dd);
    if (fabs(delta_ddr.x[0] - 1) <= k2m52) {
      double inv_ff = 1.0 / ff_ddr.x[0];
      if (midp_complement) {
        // If complement=0, inv=1 (a<->b not flipped):
        //   result_ln
        // = a log x + b log y + log((a+b-1)!) - log((a-1)!) - log((b-1)!)
        // = (k+1) log p + (n-k) log q + log(n!) - log(k!) - log((n-k-1)!)
        //
        //   log(0.5 * pmf(k))
        // = log 0.5 + k log p + (n-k) log q + log(n!) - log(k!) - log((n-k)!)
        // = log 0.5 - log p - log(n-k) + result_ln
        // = -log (2 * p * (n-k))) + result_ln
        //
        //   log(exp(result_ln - log(ff)) - 0.5 * pmf(k))
        // = log(exp(result_ln)/ff - exp(result_ln - log(2p(n-k))))
        // = log(result/ff - result/(2p(n-k)))
        // = log(result * (1/ff - 0.5/(p(n-k))))
        // = result_ln + log(1/ff - 0.5/(p(n-k)))
        double signed_p_nmk;
        if (midp_complement == inv + 1) {
          // aa<->bb, xx<->yy flip was performed earlier.
          signed_p_nmk = -aa * yy;
        } else {
          signed_p_nmk = bb * xx;
        }
        inv_ff += 0.5 / signed_p_nmk;
      }
      return inv_ff;
    }
    ff_ddr = ddr_mul(ff_ddr, delta_ddr);
  }
}

// Adaptations of DiDonato and Morris's BFRAC, which is in turn based on a
// continued fraction introduced in
//   Aroian LA (1941) Continued fractions for the incomplete beta function.
//   Annals of Mathematical Statistics, 12.
// For most larger cases, this continued fraction converges more quickly than
// binomial partial sums.  ibeta_largeab_approx() makes limited use of dd_real
// precision to address the worst precision bottlenecks, while ibeta_largeab()
// trades off speed for provably great precision.
//
// (I still have work to do in understanding the derivation and properties of
// this continued fraction well enough to take a real shot at improving e.g.
// the rather similar hypergeometric cdf calculation.)
double ibeta_largeab_approx(double aa, double bb, dd_real p_ddr, dd_real q_ddr, dd_real aq_minus_bp_ddr, uint32_t inv, uint32_t midp_complement, uint32_t return_log) {
  // normalized always true, min(aa,bb) >= 40, max(aa,bb) much larger
  // (usually cheaper to sum tail binomial terms directly with smaller
  // min(aa,bb); and Lanczos sum becomes less accurate)
  // caller responsible for guaranteeing aq - bp >= 0
  //
  // scipy.stats.binom.logcdf uses very similar C++ code, but is afflicted with
  // high overhead:
  //   >>> import exact_tests, scipy, timeit
  //   >>> timeit.timeit(lambda: exact_tests.pbinom(157000000, 419430500, 0.375, approx=True), number=10000)
  //   0.016760832993895747
  //   >>> timeit.timeit(lambda: exact_tests.pbinom(157000000, 419430500, 0.375, approx=True), number=10000)
  //   0.017603792002773844
  //   >>> timeit.timeit(lambda: exact_tests.pbinom(157000000, 419430500, 0.375, approx=True), number=10000)
  //   0.016770166999776848
  //   >>> timeit.timeit(lambda: scipy.stats.binom.logcdf(157000000, 419430500, 0.375), number=10000)
  //   1.005605333019048
  //   >>> timeit.timeit(lambda: scipy.stats.binom.logcdf(157000000, 419430500, 0.375), number=10000)
  //   0.22769695916213095
  //   >>> timeit.timeit(lambda: scipy.stats.binom.logcdf(157000000, 419430500, 0.375), number=10000)
  //   0.24197920807637274
  //   >>> timeit.timeit(lambda: scipy.stats.binom.cdf(157000000, 419430500, 0.375), number=10000)
  //   0.27701791608706117
  //   >>> timeit.timeit(lambda: scipy.stats.binom.cdf(157000000, 419430500, 0.375), number=10000)
  //   0.27656474988907576
  //   >>> timeit.timeit(lambda: scipy.stats.binom.cdf(157000000, 419430500, 0.375), number=10000)
  //   0.27791083394549787
  dd_real result_ln_ddr = ibeta_power_terms_d_ln(aa, bb, p_ddr, q_ddr, aq_minus_bp_ddr);
  const double result_incr = log(ibeta_continued_fraction_recip_d(aa, bb, p_ddr.x[0], q_ddr.x[0], aq_minus_bp_ddr, inv, midp_complement));
  result_ln_ddr = ddr_addd(result_ln_ddr, result_incr);
  if ((!inv) && return_log) {
    return result_ln_ddr.x[0];
  }
  const dd_real result_ddr = ddr_exp(result_ln_ddr);
  if (!inv) {
    return result_ddr.x[0];
  }
  const dd_real neg_result_ddr = ddr_negate(result_ddr);
  return return_log? ddr_log1p(neg_result_ddr).x[0] : ddr_addd(neg_result_ddr, 1).x[0];
}

dd_real ibeta_continued_fraction_ddr(double aa, double bb, dd_real p_ddr, dd_real q_ddr, dd_real aq_minus_bp_ddr) {
  const double cf_eps = k2m64 * (1.0 / (1 << 3));
  const dd_real aq_minus_bp_plus1_ddr = ddr_addd(aq_minus_bp_ddr, 1);
  dd_real cc_ddr = ddr_divd(ddr_muld(aq_minus_bp_plus1_ddr, aa), aa + 1);
  const dd_real two_minus_p_ddr = ddr_addd(q_ddr, 1);
  dd_real ff_ddr = cc_ddr;
  dd_real dd_ddr = ddr_maked(0);
  double mm = 1.0;
  while (1) {
    const double denom = aa + 2 * mm - 1;
    const dd_real shared_middle_term_ddr = ddr_divd(ddr_mul(ddr_mul2d(mm, bb - mm), p_ddr), denom);
    // if p_ddr is very small, precomputed p_ddr * p_ddr may underflow when
    // actual product here does not
    // (also possible for actual product to underflow)
    // (we probably just want to handle tiny p in its own function?)
    const dd_real cur_a_ddr = ddr_divd(ddr_mul(ddr_mul(ddr_mul2d(aa + mm - 1, aa + bb + mm - 1), shared_middle_term_ddr), p_ddr), denom);
    dd_real cur_b_ddr = ddr_addd(shared_middle_term_ddr, mm);
    cur_b_ddr = ddr_add(cur_b_ddr, ddr_divd(ddr_muld(ddr_add(ddr_muld(two_minus_p_ddr, mm), aq_minus_bp_plus1_ddr), aa + mm), aa + 2 * mm + 1));
    mm += 1.0;
    dd_ddr = ddr_add(ddr_mul(cur_a_ddr, dd_ddr), cur_b_ddr);
    // Algorithm should terminate when cur_a decreases to 0 due to bb == mm or
    // underflow.  At and before that point, cur_b is always positive.
    /*
    if (dd == 0.0) {
      dd = kLentzFpmin;
    }
    */
    cc_ddr = ddr_add(cur_b_ddr, ddr_accurate_div(cur_a_ddr, cc_ddr));
    /*
    if (cc == 0.0) {
      cc = kLentzFpmin;
    }
    */
    dd_ddr = ddr_accurate_div(ddr_maked(1.0), dd_ddr);
    const dd_real delta_ddr = ddr_mul(cc_ddr, dd_ddr);
    // If I correctly understand what's going on here, (delta - 1) has
    // alternating sign and decreasing magnitude, so this should ensure less
    // than cf_eps relative error is coming from incomplete evaluation of the
    // continued fraction.  (Recall that we actually need to limit the
    // logarithm's absolute error to < ~2^{-63} to achieve the desired level of
    // accuracy when DBL_MIN < p < e^{-512} and return_log=False.)
    //
    // Worst case, this takes around a million iterations.
    //
    // Update (3 Jun 2026): cf_eps tightened to 2^{-67} after comparing against
    // MPFR.  We want 1 ULP errors to require a non-negligible amount of work
    // to find.  The resulting ~5-25% speed hit is an acceptable price to pay
    // for a still-much-faster-than-MPFR function that can be treated as
    // baseline truth for most other purposes.
    //
    // The use_tdr_for_binom_lnprob() threshold should also be lowered if we
    // want to push cf_eps below 2^{-67}.
    if ((delta_ddr.x[0] == 1.0) && (fabs(delta_ddr.x[1]) <= cf_eps)) {
      return ff_ddr;
    }
    ff_ddr = ddr_mul(ff_ddr, delta_ddr);
  }
}

double ibeta_largeab(double aa, double bb, dd_real p_ddr, dd_real q_ddr, dd_real aq_minus_bp_ddr, uint32_t inv, uint32_t return_log) {
  // (a is a synonym for k+1, b is a synonym for n-k, x is a synonym for p, y
  // is a synonym for q)
  //   log((x^a)(y^b) / Beta(a,b))
  // = a log x + b log y + log((a+b-1)!) - log((a-1)!) - log((b-1)!)
  const double a_plus_b = aa + bb;
  const uint32_t p_is_half = ddr_is(p_ddr, 0.5);
  dd_real result_ln_ddr;
  // This should be consistent with use_tdr_for_binom_lnprob().
  if (a_plus_b > S_CAST(double, 1LL << 36)) {
    dd_real ddrs[5];
    ddrs[0] = ddr_lfact(a_plus_b - 1);
    ddrs[1] = ddr_negate(ddr_lfact(aa - 1));
    ddrs[2] = ddr_negate(ddr_lfact(bb - 1));
    if (p_is_half) {
      ddrs[3] = ddr_muld(_ddr_log05, a_plus_b);
    } else {
      ddrs[3] = ddr_muld(ddr_log_2arg(p_ddr, q_ddr), aa);
      ddrs[4] = ddr_muld(ddr_log_2arg(q_ddr, p_ddr), bb);
    }
    result_ln_ddr = ddr_sort_and_add(5 - p_is_half, ddrs);
  } else {
    td_real tdrs[5];
    tdrs[0] = tdr_lfact(a_plus_b - 1);
    tdrs[1] = tdr_negate(tdr_lfact(aa - 1));
    tdrs[2] = tdr_negate(tdr_lfact(bb - 1));
    if (p_is_half) {
      tdrs[3] = tdr_muld(_tdr_log05, a_plus_b);
    } else {
      if (ddr_ltd(p_ddr, 0.5)) {
        tdrs[3] = tdr_muld(tdr_log(tdr_make_dd(p_ddr)), aa);
        tdrs[4] = tdr_muld(tdr_log1p(tdr_make_dd(ddr_negate(p_ddr))), bb);
      } else {
        tdrs[3] = tdr_muld(tdr_log1p(tdr_make_dd(ddr_negate(q_ddr))), aa);
        tdrs[4] = tdr_muld(tdr_log(tdr_make_dd(q_ddr)), bb);
      }
    }
    result_ln_ddr = ddr_make_td(tdr_sort_and_add(5 - p_is_half, tdrs));
  }
  // Could tighten this bound.
  if ((result_ln_ddr.x[0] < -1418.0) && (inv || (!return_log))) {
    return (return_log || (!inv))? 0.0 : 1.0;
  }
  const dd_real ff_ddr = ibeta_continued_fraction_ddr(aa, bb, p_ddr, q_ddr, aq_minus_bp_ddr);
  result_ln_ddr = ddr_sub(result_ln_ddr, ddr_log(ff_ddr));
  if (!inv) {
    return return_log? result_ln_ddr.x[0] : ddr_exp(result_ln_ddr).x[0];
  }
  const dd_real neg_result_ddr = ddr_negate(ddr_exp(result_ln_ddr));
  return return_log? ddr_log1p(neg_result_ddr).x[0] : ddr_addd(neg_result_ddr, 1.0).x[0];
}

// This is a port of R 4.6.0 src/nmath/qnorm.c , which implements
//   Wichura, MJ (1988) Algorithm AS 241: The Percentage Points of the Normal
//   Distribution.  Applied Statistics, 37, 477-484.
// and
//   Maechler, M (2022) Asymptotic Tail Formulas For Gaussian Quantiles.
//   https://cran.r-project.org/web/packages/DPQ/vignettes/qnorm-asymp.pdf .
//
// Note that the R function this is derived from is GPL-2 licensed; thus this
// function cannot be used in scipy.  (Boost has a similar function which lacks
// the extended logp range.)
//
// It currently assumes p <= 0.5, but can trivially be modified to handle
// larger p.
//
// The function name has a trailing 'D' (for double-precision) since
// plink2_stats already has a faster single-parameter QuantileToZscore()
// function which just aims for float32-like precision.
double QuantileToZscoreD(double p_or_lnp, uint32_t p_is_log) {
  if (((!p_is_log) && (p_or_lnp >= 0.075)) || (p_is_log && (p_or_lnp >= -2.5902671654458267))) {
    const double p = p_is_log? exp(p_or_lnp) : p_or_lnp;
    assert(p <= 0.500000000000001);
    const double q = 0.5 - p;
    const double r = .180625 - q * q;
    // todo: benchmark polynomial evaluation strategies
    const double numer = POLY7(r,
                               3.387132872796366608,
                               133.14166789178437745,
                               1971.5909503065514427,
                               13731.693765509461125,
                               45921.953931549871457,
                               67265.770927008700853,
                               33430.575583588128105,
                               2509.0809287301226727);
    const double denom = POLY7(r,
                               1,
                               42.313330701600911252,
                               687.1870074920579083,
                               5394.1960214247511077,
                               21213.794301586595867,
                               39307.89580009271061,
                               28729.085735721942674,
                               5226.495278852854561);
    return -q * numer / denom;
  }
  const double lnp = p_is_log? p_or_lnp : log(p_or_lnp);
  double r = sqrt(-lnp);
  if (r <= 5) {
    r -= 1.6;
    const double numer = POLY7(r,
                               1.42343711074968357734,
                               4.6303378461565452959,
                               5.7694972214606914055,
                               3.64784832476320460504,
                               1.27045825245236838258,
                               .24178072517745061177,
                               .0227238449892691845833,
                               7.7454501427834140764e-4);
    const double denom = POLY7(r,
                               1,
                               2.05319162663775882187,
                               1.6763848301838038494,
                               .68976733498510000455,
                               .14810397642748007459,
                               .0151986665636164571966,
                               5.475938084995344946e-4,
                               1.05075007164441684324e-9);
    return -numer / denom;
  }
  if (r <= 27) {
    r -= 5;
    const double numer = POLY7(r,
                               6.6579046435011037772,
                               5.4637849111641143699,
                               1.7848265399172913358,
                               .29656057182850489123,
                               .026532189526576123093,
                               .0012426609473880784386,
                               2.71155556874348757815e-5,
                               2.01033439929228813265e-7);
    const double denom = POLY7(r,
                               1,
                               .59983220655588793769,
                               .13692988092273580531,
                               .0148753612908506148525,
                               7.868691311456132591e-4,
                               1.8463183175100546818e-5,
                               1.4215117583164458887e-7,
                               2.04426310338993978564e-15);
    return -numer / denom;
  }
  if (r >= 6.4e8) {
    return -r * kSqrt2;
  }
  const double s2 = -ldexp(lnp, 1);
  double x2 = s2 - log(k2Pi * s2);
  if (r < 36000) {
    x2 = s2 - log(k2Pi * x2) - 2.0/(2.0+x2);
    if (r < 840) {
      x2 = s2 - log(k2Pi * x2) + 2*log1p(-(1 - 1/(4+x2))/(2+x2));
      if (r < 109) {
        x2 = s2 - log(k2Pi * x2) + 2*log1p(-(1 - (1 - 5/(6+x2))/(4+x2))/(2+x2));
        if (r < 55) {
          x2 = s2 - log(k2Pi * x2) + 2*log1p(-(1 - (1 - (5 - 9/(8+x2))/(6+x2))/(4+x2))/(2+x2));
        }
      }
    }
  }
  return -sqrt(x2);
}

#ifdef __cplusplus
}
#endif
